### PR TITLE
networkd rewrite

### PR DESCRIPTION
**Pull request by RichieCahill**

### CODE REVIEW

**Review by ahuston-0 — COMMENTED** [review]
I think you missed translating the address between implementations

**Comment by RichieCahill** [comment]
> I think you missed translating the address between implementations

I didnt think we needed it

**Comment by ahuston-0** [comment]
image
it appears zerotier doesnt have an address so i think you either need to statically assign it or turn on dhcp

**Review by ahuston-0 — APPROVED** [review]
as discussed, this should be fine. we'll revisit if the k3s stuff gets screwy

**Pull request merged**
